### ISSUE TITLE
The parameter name and email can be derived from the .gitconfig file

### ISSUE THREAD

**Issue by lakruzz** [Praqma/Marcom-machine#1]
git config --global --get user.name
git config --global --get user.email

**Comment by ThaKangBaby** [comment]
Hey @lakruzz . Yes i knew this. But i assumed that this script will run on new computers which dont have Git installed, therefor the args for Git username and email. But i could make the script check for it first.

**Comment by ThaKangBaby** [comment]
@lakruzz I can check for the git config user.name and email but the problem is if i do that before git or homebrew is installed it will prompt the user to install xcode. I dont want the user to be prompted for anything so the less prompts the better.

**Comment by lakruzz** [comment]
@ThaKangBaby 

Ideally this should be data driven:

IF
  git config --global --get user.name
  git config --global --get user.email
ARE SET
  then we use them
ELSE
  Email and github handle are required parameters

Essentially that script should be able to run on _both_ new and existing Git installations.
