### ISSUE TITLE
Ruby needs to be updated before github-pages can install

### ISSUE THREAD

**Issue by lakruzz** [Praqma/Marcom-machine#2]
I had to run `sudo gem update` before the github-pages could be installe

**Comment by Nillerdadude** [comment]
Actually - that wasn't enough:

```
sudo gem update --system
```

was required, and then I still got this error:

```
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/kramdown
```

Described [here](http://stackoverflow.com/questions/32891965/error-while-executing-gem-errnoeperm-operation-not-permitted)

So I had to install `github-pages` using

```
sudo gem install -n /usr/local/bin github-pages
```

...finally it works

@lakruzz from @nillerdadude's account

**Comment by ThaKangBaby** [comment]
Added these lines to script
`sudo gem update --system` 
`sudo gem install -n /usr/local/bin github-pages`

Tested and works - Even though i did not receive this error in my test enviroment. Tested on Mac OS X El Capitan clean and with updates(10.11.6) and also the new macOS Sierra (10.12.1)
